### ISSUE TITLE
Procedure for bumping the optee branch to a recent Linux?

### ISSUE THREAD

**Issue by jneuhauser** [linaro-swg/linux#104]
Hello dev's,

in order to add our recent added STM32MP15 DHSOM based boards to OP-TEE/build and OP-TEE/manifest, it would be good to upgrade Linux to 5.18 or even better to 5.19.

Before creating a pull request, I would like to ask what is the preferred approach to this process?

The possible solutions to fully support our boards are:
1. backport needed patches to 5.17 and define OP-TEE resources.
2. bump Linux to 5.18 or even better to 5.19 and define OP-TEE resources

Thanks in advance,
Johann

**Comment by jforissier** [comment]
Hello @jneuhauser,

Short answer: 2.

I take care of rebasing the `optee` branch of this repo periodically, usually shortly before OP-TEE release time. The `optee` branch is a convenience for the dev/test environment (which is as you mentioned, the build and manifest Gits). In principle we only want DT patches in here which are not acceptable upstream -- in any case, the less changes compared to upstream the better. It does happen that we merge features here temporarily but any OP-TEE driver patch should really go to the LKML directly. So I will rebase onto 5.19 ; when done, if you would like to submit DT patches for your platform please create a PR here.

**Comment by jneuhauser** [comment]
Thank you for the precise and quick response.

**Comment by jforissier** [comment]
> I will rebase onto 5.19

FYI, done.

**Comment by jneuhauser** [comment]
You are really very fast. Thank you.
