### ISSUE TITLE
Code related to the optee benchmark is added to the Linux operating system. As a result, a compilation error is reported.

### ISSUE THREAD

**Issue by hearyouagain** [linaro-swg/linux#111]
hi，i had add the bench.c and its related codes into linux，but there are something wrong when compilation：
  LD      vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1
aarch64-v01c01-linux-musl-ld: warning: -z norelro ignored
aarch64-v01c01-linux-musl-ld: Unexpected GOT/PLT entries detected!
aarch64-v01c01-linux-musl-ld: Unexpected run-time procedure linkages detected!
aarch64-v01c01-linux-musl-ld: drivers/tee/optee/bench.o: in function `optee_bm_timestamp':
bench.c:(.text+0x14c): undefined reference to `__aarch64_ldadd8_acq_rel'
Makefile:1185: recipe for target 'vmlinux' failed

i dont know how to fix it

**Comment by hearyouagain** [comment]
i had tried to add -march=armv8-a to CFLAGS and -latomic to LDFALGS， but it make no sense

**Comment by hearyouagain** [comment]
this issue had been solved， but when i enable CFG_TEE_BENCHMARK in linux optee_os optee_client，but the benchmark always have error：
[Benchmark] INFO: 1. Opening Benchmark Static TA...
[Benchmark] INFO: 2. Allocating per-core buffers, cores detected = 2
E/TC:? 00 get_rpc_alloc_res:645 RPC allocation failed. Non-secure world result: ret=0xffff0006 ret_origin=0x2
E/TC:? 00 alloc_benchmark_buffer:72 Benchmark: can't create mobj for timestamp buffer
[Benchmark] ERROR: TEEC_InvokeCommand: 0xffff000c

**Comment by jenswi-linaro** [comment]
I'm sorry, but the benchmark isn't maintained any longer. It should hopefully not be too hard to get it to work again if someone is willing to maintain it.

**Comment by hearyouagain** [comment]
fine， thanks a lot
