### ISSUE TITLE
Kernel panic on i.MX6 with OPTEE drivers

### ISSUE THREAD

**Issue by NightEugene** [linaro-swg/linux#12]
Hello,

I am trying to run OPTEE-OS on i.MX6Q Sabre Automotive board.
I added following lines to imx6qdl-sabreauto.dtsi:

```
reserved-memory {
    #address-cells = <1>;
    #size-cells = <1>;
    ranges;

    optee@0x8D000000 {
        reg = <0x8D000000 0x03000000>;
    };
};

firmware {
    optee {
        compatible = "linaro,optee-tz";
        method = "smc";
    };
};
```

Kernel fails on invoke_fn(OPTEE_SMC_CALLS_UID, 0, 0, 0, 0, 0, 0, 0, &res);

I use signed u-boot and zImage, but I don't burn fuses. My boot security configuration is Open.
I need enable secure boot for running optee drivers? Or my dts file is wrong?

[linux_panic_optee.txt](https://github.com/linaro-swg/linux/files/318564/linux_panic_optee.txt)

**Comment by jenswi-linaro** [comment]
Hi,

It looks like Linux is booting in secure mode, that is, OP-TEE isn't loaded.

**Comment by NightEugene** [comment]
> It looks like Linux is booting in secure mode, that is, OP-TEE isn't loaded.

How you determined this?

I run op-tee like in this instruction https://github.com/OP-TEE/optee_os#46-freescale-mx6ul-evk

But I made few changes in my core/arch/arm/plat-imx/platform_config.h in optee-os:

```
#define DRAM0_BASE            0x10000000
#define DRAM0_SIZE            0x80000000

#define TZDRAM_BASE           0x8D000000
#define TZDRAM_SIZE           0x03000000
```

```
U-Boot 2015.04-14471-g16470a1-dirty (Jun 15 2016 - 18:23:03)

CPU:   Freescale i.MX6Q rev1.2 at 792 MHz
CPU:   Temperature 46 C
Reset cause: POR
Board: MX6Q-Sabreauto revA
I2C:   ready
DRAM:  2 GiB
PMIC:  PFUZE100 ID=0x10
NAND:  0 MiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
*** Warning - bad CRC, using default environment

No panel detected: default to Hannstar-XGA
Display: Hannstar-XGA (1024x768)
In:    serial
Out:   serial
Err:   serial
switch to partitions #0, OK
mmc1 is current device
Net:   FEC [PRIME]
Normal Boot
Hit any key to stop autoboot:  0 
=> hab_status 

Secure boot disabled

HAB Configuration: 0xf0, HAB State: 0x66
No HAB Events Found!
=> fatload mmc 1:1 0x8D000000 optee.bin
reading optee.bin
203812 bytes read in 92 ms (2.1 MiB/s)
=> boot
```

That all what I am doing. But I can not understand who runs optee-os(
Thanks a lot for your attention!

**Comment by jenswi-linaro** [comment]
This line says it all:

```
[    1.932114] Flags: nZCv  IRQs off  FIQs off  Mode MON_32  ISA ARM  Segment none
```

The SMC was trapped by the Linux kernel instead of the secure OS, that means that the kernel is running in secure mode.

**Comment by NightEugene** [comment]
Thanks a lot! Really, OP-TEE isn't loaded.
My u-boot hasn't possibility to run OP-TEE. Here is a patch that can help run OP-TEE from u-boot on imx6: https://github.com/MrVan/uboot/commit/4f016adae573aaadd7bf6a37f8c58a882b391ae6
