### ISSUE TITLE
optee branch rebased on v6.12

### ISSUE THREAD

**Issue by jenswi-linaro** [linaro-swg/linux#120]
I've prepared a rebased optee branch on v6.12 at https://github.com/linaro-swg/linux/tree/wip/optee-v6.12.
Please let me know if we're happy with the result so we have it in place with time to spare before the next OP-TEE release.

**Comment by jockebech** [comment]
Looks like the same series with been carrying for some time now, so no concerns from me, all looking good from what I can see.

**Comment by jforissier** [comment]
LGTM

**Comment by jenswi-linaro** [comment]
Thanks, I'll push the update to `optee`, it will effectively be rebased from v6.6 to v6.12.

**Comment by jenswi-linaro** [comment]
push -f fails with:
```
 ! [remote rejected]           wip/optee-v6.12 -> optee (protected branch hook declined)
```
How do I work around that, temporarily unprotecting the `optee` branch?

**Comment by jockebech** [comment]
> How do I work around that, temporarily unprotecting the `optee` branch?

Yes, you'll find that in the settings, disable it and then re-enable it again once done. We've that enabled in some places for our own sake, to avoid wiping/replacing things by mistake.

**Comment by jenswi-linaro** [comment]
Done, thanks for the help.
