### ISSUE TITLE
Rebasing optee branch onto kernel 5.5

### ISSUE THREAD

**Issue by jforissier** [linaro-swg/linux#71]
Hi,

I have pushed a new branch called [wip/optee-v5.5](https://github.com/linaro-swg/linux/commits/wip/optee-v5.5) which is our current linaro-swg/linux.git branch optee rebased onto upstream kernel 5.5 (and with [`upstream-tee-subsys-patches.txt`](https://github.com/linaro-swg/linux/blob/wip/optee-v5.5/upstream-tee-subsys-patches.txt) updated).

Sanity-tested on QEMU, HiKey and HiKey960. I'd like to replace the tip of the optee branch with this new one soon.

If anyone has any issue with that, please comment here! Thanks.

**Comment by jockebech** [comment]
I have no issue with it, but still commenting here :)

**Comment by jenswi-linaro** [comment]
A few of the commits are fixups to earlier commits.
For instance:
- "OP-TEE Benchmark **not for mainline**"
- "tee: optee: optee_bench.h: remove useless include **not for mainline**"

and
- "tee: new ioctl to a register tee_shm from a dmabuf file descriptor"
- "tee: fix unbalanced context refcount in register shm from fd"

and
- "tee: support of allocating DMA shared buffers **not for mainline**"
- "tee: support of allocating DMA shared buffers **not for mainline**"

How about squashing those?

**Comment by jforissier** [comment]
@jenswi-linaro yup, good idea, will do.

**Comment by jforissier** [comment]
Commits squashed, forced pushed to `wip/optee-v5.5`.

**Comment by jenswi-linaro** [comment]
Looks good to me.

**Comment by jforissier** [comment]
Force-pushed `wip/optee-v5.5` to branch [`optee`](https://github.com/linaro-swg/linux/commits/optee). Previous tip of that branch saved as [`branch-optee-v5.1-20200204`](https://github.com/linaro-swg/linux/commits/branch-optee-v5.1-20200204).
