### ISSUE TITLE
rpi3-optee-4.14 branch cannot compile

### ISSUE THREAD

**Issue by ShaleXIONG** [linaro-swg/linux#78]
rpi3-optee-4.14 branch cannot compile, due to, possibly the last commit. Especially there is no `sec_caps`
in  the definition  of struct optee in optee_private.h.

**Comment by jforissier** [comment]
Hi @ShaleXIONG,

Thanks for reporting this issue. I think we need this patch: https://github.com/linaro-swg/linux/commit/d885cc5e0759fc19badadddb60a64344b551469b and hopefully not more.

Could you please try it? I don't have a RPi3 board to test.

**Comment by ShaleXIONG** [comment]
It compiles now. I did not check the entire process, i.e. actually run the test on RPi3 board but I assume it should work.

**Comment by jforissier** [comment]
Thanks for testing, I have applied the patch on top of https://github.com/linaro-swg/linux/tree/rpi3-optee-4.14.
