### ISSUE TITLE
Rebasing optee branch onto upstream kernel v5.9

### ISSUE THREAD

**Issue by jforissier** [linaro-swg/linux#81]
Since it is OP-TEE release time again, we may as well update our Linux branch. Therefore I have rebased the `optee` branch (which is currently based on Linux v5.5) onto the latest upstream (v5.9-rc8).

The new branch is [`wip/optee-v5.9-rc8`](https://github.com/linaro-swg/linux/commits/wip/optee-v5.9-rc8). I will use this branch when testing OP-TEE on QEMU, QEMUv8, HiKey and HiKey960. I have NOT touched the `optee` branch yet.

@etienne-lms a couple of patches caused conflicts due to different file names upstream and some changes already applied:
 5973cd5de376 ARM: dts: stm32: Define OP-TEE resources on stm32mp15 and enable on DK2
 b7b9d3177a87 ARM: dts: stm32: bump PSCI to version 1.0 on stm32mp15x
Can you please check if what I have done is OK? The 2nd patch seems to be upstream already so it does not appear in the rebased branch.

**Comment by etienne-lms** [comment]
Hi @jforissier,
I'll look at that, sorry for the delay...

**Comment by jforissier** [comment]
@etienne-lms no worries.
Note, in the meantime Linux v5.9 was released so I have pushed [wip/optee-v5.9](https://github.com/linaro-swg/linux/commits/wip/optee-v5.9).

**Comment by jforissier** [comment]
optee branch updated.
